spring:
  application:
    name: order-server

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

server:
  port: 8080